### ISSUE TITLE
Don't include compiled code in version control - use a `gh-pages` branch or something for that.

### ISSUE THREAD

**Issue by Lazerbeak12345** [Lazerbeak12345/pixelmanipulator#60]

**Comment by Lazerbeak12345** [comment]
`gulp-gh-pages` seems to be the way to go. TBH I don't 100 percent trust it will do what I want, how I want, so they get a free code review :wink:

**Comment by Lazerbeak12345** [comment]
Ok, it's exactly what I want. I've just got to set it up now.

**Comment by Lazerbeak12345** [comment]
Upon attempt, this is the error message I get:

```
[17:46:52] TypeError: Cannot read properties of null (reading '0')
    at Function.module.exports.Commit.actor (/home/nate/projects/pixelmanipulator/node_modules/gift/lib/commit.js:145:56)
    at Function.module.exports.Commit.parse_commits (/home/nate/projects/pixelmanipulator/node_modules/gift/lib/commit.js:111:21)
    at /home/nate/projects/pixelmanipulator/node_modules/gift/lib/commit.js:55:39
    at ChildProcess.exithandler (node:child_process:388:7)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:537:15)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:537:15)
```

Seeing how delayed [the most recent PR](https://github.com/shinnn/gulp-gh-pages/pull/135) is (1 year old) on that repo, I'll just have to find a different solution.

See the [gulp-gh-pages](https://github.com/Lazerbeak12345/pixelmanipulator/tree/gulp-gh-pages) branch for where this attempt is at.
